DROP TABLE IF EXISTS INSTITUTION;
DROP TABLE IF EXISTS INSTITUTION_USER;

CREATE TABLE INSTITUTION (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    code INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    status INT NULL
);

CREATE TABLE INSTITUTION_USER (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    username VARCHAR(MAX) NOT NULL,
    password VARCHAR(MAX) NOT NULL
);